[package]
name = "douady"
version = "0.1.0"
authors = ["Filip Szczepański <jazz2rulez@gmail.com>"]
license = "GPL-3.0"
edition = "2021"

[dependencies]
rug = "1.17.0"
vizia = { git = "https://github.com/vizia/vizia/" }
imgref = "1.9.4"
